-- INSERTS GENERALES

--INSERT DE IDIOMAS PARA LA APLICACION
INSERT INTO IDIOMAS VALUES (1, 'ESPAÑOL', 'ES');
INSERT INTO IDIOMAS VALUES (2, 'INGLES', 'EN');

-- INSERT DE TIPOS DE PROPIEDADES
INSERT INTO TIPO VALUES (1, 'CASA');
INSERT INTO TIPO VALUES (2, 'APARTAMENTO');
INSERT INTO TIPO VALUES (3, 'LOTE');

-- INSERT DE TIPOS DE MONEDA
INSERT INTO MONEDA VALUES (1, 'PESO COLOMBIANO', 'COP');
INSERT INTO MONEDA VALUES (2, 'DOLAR AMERICANO', 'USD');

COMMIT;